[package]
name = "kakure-core"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
byteorder = "1.5.0"
gimli = "0.32.3"
goblin = { workspace = true }
log = { workspace = true }
